apiVersion: v1
kind: Service
metadata:
  name: apps-service
  labels:
    app: apps
spec:
  selector:
    app: apps
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: apps