apiVersion: v1
kind: Service
metadata:
  name: apps-service
  namespace: argocd
spec:
  selector:
    app: apps
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  - name: app-port
    protocol: TCP
    port: 8086
  - targetPort: 3000