ingressShim:
  defaultIssuerKind: dns01
  defaultIssuerProvider: route53

pullSecrets: [true]

extraArgs:
- --dns01-recursive-nameservers=8.8.8.8:53"
- --dns01-recursive-nameservers-only"

namespace: cert-manager

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::648767092427:role/ClusterStack-HelloEKScertmanagerRoleDFDC789B-2nqHjoBBNocG
